### ISSUE TITLE
What would be the preferred to to ducktype if a contract is a 404?

### ISSUE THREAD

**Issue by geertbrit** [Pandora-Labs-Org/erc404#21]
For indexers of all sorts it's useful to be able to 'somewhat reliably' be able to ducktype if a contract is a 404. 
What would be the preferred way here?

**Comment by mathdroid** [comment]
from me in tg:

thinking out loud:

check if they have
- name
- symbol
- totalSupply

then check if they have
- ownerOf (unique to 721)
- transfer (unique to 20)

optional
- decimals (only some 721 has it)

@0xacme added:

404 v2 implements erc165 and returns that it supports ierc404 so that will be the future way to determine if a token is a 404
